server:
  port: 9010

spring:
  data:
    redis:
      host: localhost
      port: 6379
scheduler:
  enabled: true

---
spring:
  config:
    activate:
      on-profile: test
  data:
    redis:
      host: localhost
      port: 63790
scheduler:
  enabled: false